// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtb_radix2_top.h for the primary calling header

#ifndef VERILATED_VTB_RADIX2_TOP___024ROOT_H_
#define VERILATED_VTB_RADIX2_TOP___024ROOT_H_  // guard

#include "verilated.h"
#include "verilated_timing.h"


class Vtb_radix2_top__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtb_radix2_top___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*0:0*/ tb_radix2_top__DOT__clock;
        CData/*0:0*/ tb_radix2_top__DOT__reset;
        CData/*0:0*/ tb_radix2_top__DOT__input_en;
        CData/*0:0*/ tb_radix2_top__DOT__frame_ready;
        CData/*0:0*/ tb_radix2_top__DOT__input_en_d;
        CData/*0:0*/ tb_radix2_top__DOT__output_en_d;
        CData/*0:0*/ tb_radix2_top__DOT__counting_latency;
        CData/*0:0*/ tb_radix2_top__DOT__counting_active;
        CData/*0:0*/ tb_radix2_top__DOT__dut__DOT____Vcellout__gen_stages__BRA__0__KET____DOT__stage_inst__output_en;
        CData/*0:0*/ tb_radix2_top__DOT__dut__DOT____Vcellout__gen_stages__BRA__1__KET____DOT__stage_inst__output_en;
        CData/*0:0*/ tb_radix2_top__DOT__dut__DOT____Vcellout__gen_stages__BRA__2__KET____DOT__stage_inst__output_en;
        CData/*0:0*/ tb_radix2_top__DOT__dut__DOT____Vcellout__gen_stages__BRA__3__KET____DOT__stage_inst__output_en;
        CData/*0:0*/ tb_radix2_top__DOT__dut__DOT____Vcellout__gen_stages__BRA__4__KET____DOT__stage_inst__output_en;
        CData/*0:0*/ tb_radix2_top__DOT__dut__DOT____Vcellout__gen_stages__BRA__5__KET____DOT__stage_inst__output_en;
        CData/*0:0*/ tb_radix2_top__DOT__dut__DOT____Vcellout__gen_stages__BRA__6__KET____DOT__stage_inst__output_en;
        CData/*0:0*/ tb_radix2_top__DOT__dut__DOT____Vcellout__gen_stages__BRA__7__KET____DOT__stage_inst__output_en;
        CData/*0:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__1__KET____DOT__stage_inst__DOT__stride_segment_counter;
        CData/*0:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__1__KET____DOT__stage_inst__DOT__butterfly_op_counter;
        CData/*6:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__1__KET____DOT__stage_inst__DOT__flush_counter;
        CData/*0:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__1__KET____DOT__stage_inst__DOT__butterfly_op_counter_en;
        CData/*7:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__1__KET____DOT__stage_inst__DOT__wr;
        CData/*7:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__1__KET____DOT__stage_inst__DOT__wi;
        CData/*7:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__1__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__w0re_d;
        CData/*1:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__2__KET____DOT__stage_inst__DOT__stride_segment_counter;
        CData/*1:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__2__KET____DOT__stage_inst__DOT__butterfly_op_counter;
        CData/*6:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__2__KET____DOT__stage_inst__DOT__flush_counter;
        CData/*0:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__2__KET____DOT__stage_inst__DOT__butterfly_op_counter_en;
        CData/*7:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__2__KET____DOT__stage_inst__DOT__wr;
        CData/*7:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__2__KET____DOT__stage_inst__DOT__wi;
        CData/*7:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__2__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__w0re_d;
        CData/*2:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__3__KET____DOT__stage_inst__DOT__stride_segment_counter;
        CData/*2:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__3__KET____DOT__stage_inst__DOT__butterfly_op_counter;
        CData/*6:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__3__KET____DOT__stage_inst__DOT__flush_counter;
        CData/*0:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__3__KET____DOT__stage_inst__DOT__butterfly_op_counter_en;
        CData/*7:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__3__KET____DOT__stage_inst__DOT__wr;
        CData/*7:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__3__KET____DOT__stage_inst__DOT__wi;
        CData/*7:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__3__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__w0re_d;
        CData/*3:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__4__KET____DOT__stage_inst__DOT__stride_segment_counter;
        CData/*3:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__4__KET____DOT__stage_inst__DOT__butterfly_op_counter;
        CData/*6:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__4__KET____DOT__stage_inst__DOT__flush_counter;
        CData/*0:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__4__KET____DOT__stage_inst__DOT__butterfly_op_counter_en;
        CData/*7:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__4__KET____DOT__stage_inst__DOT__wr;
        CData/*7:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__4__KET____DOT__stage_inst__DOT__wi;
        CData/*7:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__4__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__w0re_d;
        CData/*4:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__5__KET____DOT__stage_inst__DOT__stride_segment_counter;
        CData/*4:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__5__KET____DOT__stage_inst__DOT__butterfly_op_counter;
        CData/*6:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__5__KET____DOT__stage_inst__DOT__flush_counter;
        CData/*0:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__5__KET____DOT__stage_inst__DOT__butterfly_op_counter_en;
        CData/*7:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__5__KET____DOT__stage_inst__DOT__wr;
        CData/*7:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__5__KET____DOT__stage_inst__DOT__wi;
        CData/*7:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__5__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__w0re_d;
        CData/*5:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__6__KET____DOT__stage_inst__DOT__stride_segment_counter;
        CData/*5:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__6__KET____DOT__stage_inst__DOT__butterfly_op_counter;
        CData/*6:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__6__KET____DOT__stage_inst__DOT__flush_counter;
        CData/*0:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__6__KET____DOT__stage_inst__DOT__butterfly_op_counter_en;
        CData/*7:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__6__KET____DOT__stage_inst__DOT__wr;
        CData/*7:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__6__KET____DOT__stage_inst__DOT__wi;
        CData/*7:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__6__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__w0re_d;
        CData/*6:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__7__KET____DOT__stage_inst__DOT__stride_segment_counter;
        CData/*6:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__7__KET____DOT__stage_inst__DOT__butterfly_op_counter;
        CData/*6:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__7__KET____DOT__stage_inst__DOT__flush_counter;
        CData/*0:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__7__KET____DOT__stage_inst__DOT__butterfly_op_counter_en;
        CData/*7:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__7__KET____DOT__stage_inst__DOT__wr;
        CData/*7:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__7__KET____DOT__stage_inst__DOT__wi;
    };
    struct {
        CData/*7:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__7__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__w0re_d;
        CData/*0:0*/ __Vdly__tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__1__KET____DOT__stage_inst__DOT__butterfly_op_counter_en;
        CData/*0:0*/ __Vdly__tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__2__KET____DOT__stage_inst__DOT__butterfly_op_counter_en;
        CData/*0:0*/ __Vdly__tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__3__KET____DOT__stage_inst__DOT__butterfly_op_counter_en;
        CData/*0:0*/ __Vdly__tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__4__KET____DOT__stage_inst__DOT__butterfly_op_counter_en;
        CData/*0:0*/ __Vdly__tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__5__KET____DOT__stage_inst__DOT__butterfly_op_counter_en;
        CData/*0:0*/ __Vdly__tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__6__KET____DOT__stage_inst__DOT__butterfly_op_counter_en;
        CData/*0:0*/ __Vdly__tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__7__KET____DOT__stage_inst__DOT__butterfly_op_counter_en;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_radix2_top__DOT__clock__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_radix2_top__DOT__reset__0;
        CData/*0:0*/ __VactContinue;
        SData/*15:0*/ tb_radix2_top__DOT__input_real_0;
        SData/*15:0*/ tb_radix2_top__DOT__input_real_1;
        SData/*15:0*/ tb_radix2_top__DOT__input_imag_0;
        SData/*15:0*/ tb_radix2_top__DOT__input_imag_1;
        SData/*15:0*/ tb_radix2_top__DOT____Vlvbound_he6a872a1__0;
        SData/*15:0*/ tb_radix2_top__DOT____Vlvbound_h1a871cae__0;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT____Vcellout__gen_stages__BRA__0__KET____DOT__stage_inst__output_imag_1;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT____Vcellout__gen_stages__BRA__0__KET____DOT__stage_inst__output_imag_0;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT____Vcellout__gen_stages__BRA__0__KET____DOT__stage_inst__output_real_1;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT____Vcellout__gen_stages__BRA__0__KET____DOT__stage_inst__output_real_0;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT____Vcellout__gen_stages__BRA__1__KET____DOT__stage_inst__output_imag_1;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT____Vcellout__gen_stages__BRA__1__KET____DOT__stage_inst__output_imag_0;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT____Vcellout__gen_stages__BRA__1__KET____DOT__stage_inst__output_real_1;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT____Vcellout__gen_stages__BRA__1__KET____DOT__stage_inst__output_real_0;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT____Vcellout__gen_stages__BRA__2__KET____DOT__stage_inst__output_imag_1;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT____Vcellout__gen_stages__BRA__2__KET____DOT__stage_inst__output_imag_0;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT____Vcellout__gen_stages__BRA__2__KET____DOT__stage_inst__output_real_1;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT____Vcellout__gen_stages__BRA__2__KET____DOT__stage_inst__output_real_0;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT____Vcellout__gen_stages__BRA__3__KET____DOT__stage_inst__output_imag_1;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT____Vcellout__gen_stages__BRA__3__KET____DOT__stage_inst__output_imag_0;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT____Vcellout__gen_stages__BRA__3__KET____DOT__stage_inst__output_real_1;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT____Vcellout__gen_stages__BRA__3__KET____DOT__stage_inst__output_real_0;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT____Vcellout__gen_stages__BRA__4__KET____DOT__stage_inst__output_imag_1;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT____Vcellout__gen_stages__BRA__4__KET____DOT__stage_inst__output_imag_0;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT____Vcellout__gen_stages__BRA__4__KET____DOT__stage_inst__output_real_1;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT____Vcellout__gen_stages__BRA__4__KET____DOT__stage_inst__output_real_0;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT____Vcellout__gen_stages__BRA__5__KET____DOT__stage_inst__output_imag_1;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT____Vcellout__gen_stages__BRA__5__KET____DOT__stage_inst__output_imag_0;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT____Vcellout__gen_stages__BRA__5__KET____DOT__stage_inst__output_real_1;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT____Vcellout__gen_stages__BRA__5__KET____DOT__stage_inst__output_real_0;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT____Vcellout__gen_stages__BRA__6__KET____DOT__stage_inst__output_imag_1;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT____Vcellout__gen_stages__BRA__6__KET____DOT__stage_inst__output_imag_0;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT____Vcellout__gen_stages__BRA__6__KET____DOT__stage_inst__output_real_1;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT____Vcellout__gen_stages__BRA__6__KET____DOT__stage_inst__output_real_0;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT____Vcellout__gen_stages__BRA__7__KET____DOT__stage_inst__output_imag_1;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT____Vcellout__gen_stages__BRA__7__KET____DOT__stage_inst__output_imag_0;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT____Vcellout__gen_stages__BRA__7__KET____DOT__stage_inst__output_real_1;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT____Vcellout__gen_stages__BRA__7__KET____DOT__stage_inst__output_real_0;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__0__KET____DOT__stage_inst__DOT__y0_re;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__0__KET____DOT__stage_inst__DOT__y0_im;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__0__KET____DOT__stage_inst__DOT__y1_re;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__0__KET____DOT__stage_inst__DOT__y1_im;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__1__KET____DOT__stage_inst__DOT__y0_re;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__1__KET____DOT__stage_inst__DOT__y0_im;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__1__KET____DOT__stage_inst__DOT__x1_re;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__1__KET____DOT__stage_inst__DOT__x1_im;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__1__KET____DOT__stage_inst__DOT__y1_re;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__1__KET____DOT__stage_inst__DOT__y1_im;
        SData/*8:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__1__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__sum_w0_in;
        SData/*8:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__1__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__diff_w0_in;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__1__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__a_re_d;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__1__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__a_im_d;
    };
    struct {
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__2__KET____DOT__stage_inst__DOT__y0_re;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__2__KET____DOT__stage_inst__DOT__y0_im;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__2__KET____DOT__stage_inst__DOT__x1_re;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__2__KET____DOT__stage_inst__DOT__x1_im;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__2__KET____DOT__stage_inst__DOT__y1_re;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__2__KET____DOT__stage_inst__DOT__y1_im;
        SData/*8:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__2__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__sum_w0_in;
        SData/*8:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__2__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__diff_w0_in;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__2__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__a_re_d;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__2__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__a_im_d;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__3__KET____DOT__stage_inst__DOT__y0_re;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__3__KET____DOT__stage_inst__DOT__y0_im;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__3__KET____DOT__stage_inst__DOT__x1_re;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__3__KET____DOT__stage_inst__DOT__x1_im;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__3__KET____DOT__stage_inst__DOT__y1_re;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__3__KET____DOT__stage_inst__DOT__y1_im;
        SData/*8:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__3__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__sum_w0_in;
        SData/*8:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__3__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__diff_w0_in;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__3__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__a_re_d;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__3__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__a_im_d;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__4__KET____DOT__stage_inst__DOT__y0_re;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__4__KET____DOT__stage_inst__DOT__y0_im;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__4__KET____DOT__stage_inst__DOT__x1_re;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__4__KET____DOT__stage_inst__DOT__x1_im;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__4__KET____DOT__stage_inst__DOT__y1_re;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__4__KET____DOT__stage_inst__DOT__y1_im;
        SData/*8:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__4__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__sum_w0_in;
        SData/*8:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__4__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__diff_w0_in;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__4__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__a_re_d;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__4__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__a_im_d;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__5__KET____DOT__stage_inst__DOT__y0_re;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__5__KET____DOT__stage_inst__DOT__y0_im;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__5__KET____DOT__stage_inst__DOT__x1_re;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__5__KET____DOT__stage_inst__DOT__x1_im;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__5__KET____DOT__stage_inst__DOT__y1_re;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__5__KET____DOT__stage_inst__DOT__y1_im;
        SData/*8:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__5__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__sum_w0_in;
        SData/*8:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__5__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__diff_w0_in;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__5__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__a_re_d;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__5__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__a_im_d;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__6__KET____DOT__stage_inst__DOT__y0_re;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__6__KET____DOT__stage_inst__DOT__y0_im;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__6__KET____DOT__stage_inst__DOT__x1_re;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__6__KET____DOT__stage_inst__DOT__x1_im;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__6__KET____DOT__stage_inst__DOT__y1_re;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__6__KET____DOT__stage_inst__DOT__y1_im;
        SData/*8:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__6__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__sum_w0_in;
        SData/*8:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__6__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__diff_w0_in;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__6__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__a_re_d;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__6__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__a_im_d;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__7__KET____DOT__stage_inst__DOT__y0_re;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__7__KET____DOT__stage_inst__DOT__y0_im;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__7__KET____DOT__stage_inst__DOT__x1_re;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__7__KET____DOT__stage_inst__DOT__x1_im;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__7__KET____DOT__stage_inst__DOT__y1_re;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__7__KET____DOT__stage_inst__DOT__y1_im;
        SData/*8:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__7__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__sum_w0_in;
        SData/*8:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__7__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__diff_w0_in;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__7__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__a_re_d;
        SData/*15:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__7__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__a_im_d;
        IData/*31:0*/ tb_radix2_top__DOT__total_samples_read;
        IData/*31:0*/ tb_radix2_top__DOT__output_count;
        IData/*31:0*/ tb_radix2_top__DOT__out_file_id;
        IData/*31:0*/ tb_radix2_top__DOT__scan_count;
    };
    struct {
        IData/*31:0*/ tb_radix2_top__DOT__t_i;
        IData/*31:0*/ tb_radix2_top__DOT__t_r;
        IData/*31:0*/ tb_radix2_top__DOT__k;
        IData/*31:0*/ tb_radix2_top__DOT__window_count;
        IData/*31:0*/ tb_radix2_top__DOT__write_offset;
        IData/*31:0*/ tb_radix2_top__DOT__print_offset;
        IData/*31:0*/ tb_radix2_top__DOT__file_id;
        IData/*31:0*/ tb_radix2_top__DOT__t_latency;
        IData/*31:0*/ tb_radix2_top__DOT__t_active;
        IData/*24:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__1__KET____DOT__stage_inst__DOT__b0__DOT____Vcellout__stage_gen__DOT__cheap_mult__DOT__u_cmul__out_a_im;
        IData/*24:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__1__KET____DOT__stage_inst__DOT__b0__DOT____Vcellout__stage_gen__DOT__cheap_mult__DOT__u_cmul__out_a_re;
        IData/*16:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__1__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__sum_a_in;
        IData/*24:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__1__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__k1_a;
        IData/*24:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__1__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__k2_a;
        IData/*24:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__1__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__k3_a;
        IData/*24:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__2__KET____DOT__stage_inst__DOT__b0__DOT____Vcellout__stage_gen__DOT__cheap_mult__DOT__u_cmul__out_a_im;
        IData/*24:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__2__KET____DOT__stage_inst__DOT__b0__DOT____Vcellout__stage_gen__DOT__cheap_mult__DOT__u_cmul__out_a_re;
        IData/*16:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__2__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__sum_a_in;
        IData/*24:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__2__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__k1_a;
        IData/*24:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__2__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__k2_a;
        IData/*24:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__2__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__k3_a;
        IData/*24:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__3__KET____DOT__stage_inst__DOT__b0__DOT____Vcellout__stage_gen__DOT__cheap_mult__DOT__u_cmul__out_a_im;
        IData/*24:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__3__KET____DOT__stage_inst__DOT__b0__DOT____Vcellout__stage_gen__DOT__cheap_mult__DOT__u_cmul__out_a_re;
        IData/*16:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__3__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__sum_a_in;
        IData/*24:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__3__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__k1_a;
        IData/*24:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__3__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__k2_a;
        IData/*24:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__3__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__k3_a;
        IData/*24:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__4__KET____DOT__stage_inst__DOT__b0__DOT____Vcellout__stage_gen__DOT__cheap_mult__DOT__u_cmul__out_a_im;
        IData/*24:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__4__KET____DOT__stage_inst__DOT__b0__DOT____Vcellout__stage_gen__DOT__cheap_mult__DOT__u_cmul__out_a_re;
        IData/*16:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__4__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__sum_a_in;
        IData/*24:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__4__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__k1_a;
        IData/*24:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__4__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__k2_a;
        IData/*24:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__4__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__k3_a;
        IData/*24:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__5__KET____DOT__stage_inst__DOT__b0__DOT____Vcellout__stage_gen__DOT__cheap_mult__DOT__u_cmul__out_a_im;
        IData/*24:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__5__KET____DOT__stage_inst__DOT__b0__DOT____Vcellout__stage_gen__DOT__cheap_mult__DOT__u_cmul__out_a_re;
        IData/*16:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__5__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__sum_a_in;
        IData/*24:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__5__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__k1_a;
        IData/*24:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__5__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__k2_a;
        IData/*24:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__5__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__k3_a;
        IData/*24:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__6__KET____DOT__stage_inst__DOT__b0__DOT____Vcellout__stage_gen__DOT__cheap_mult__DOT__u_cmul__out_a_im;
        IData/*24:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__6__KET____DOT__stage_inst__DOT__b0__DOT____Vcellout__stage_gen__DOT__cheap_mult__DOT__u_cmul__out_a_re;
        IData/*16:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__6__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__sum_a_in;
        IData/*24:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__6__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__k1_a;
        IData/*24:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__6__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__k2_a;
        IData/*24:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__6__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__k3_a;
        IData/*24:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__7__KET____DOT__stage_inst__DOT__b0__DOT____Vcellout__stage_gen__DOT__cheap_mult__DOT__u_cmul__out_a_im;
        IData/*24:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__7__KET____DOT__stage_inst__DOT__b0__DOT____Vcellout__stage_gen__DOT__cheap_mult__DOT__u_cmul__out_a_re;
        IData/*16:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__7__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__sum_a_in;
        IData/*24:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__7__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__k1_a;
        IData/*24:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__7__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__k2_a;
        IData/*24:0*/ tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__7__KET____DOT__stage_inst__DOT__b0__DOT__stage_gen__DOT__cheap_mult__DOT__u_cmul__DOT__slow_dsp__DOT__no_carry_save_mult__DOT__k3_a;
        IData/*31:0*/ __VactIterCount;
        VlUnpacked<SData/*15:0*/, 512> tb_radix2_top__DOT__output_real;
        VlUnpacked<SData/*15:0*/, 512> tb_radix2_top__DOT__output_imag;
        VlUnpacked<SData/*15:0*/, 1256> tb_radix2_top__DOT__file_real_data;
        VlUnpacked<SData/*15:0*/, 1256> tb_radix2_top__DOT__file_imag_data;
        VlUnpacked<CData/*0:0*/, 1> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__0__KET____DOT__stage_inst__DOT__b0__DOT__u_delay_start__DOT__genblk1__DOT__delay_line;
        VlUnpacked<CData/*7:0*/, 2> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__1__KET____DOT__stage_inst__DOT__w_real;
        VlUnpacked<CData/*7:0*/, 2> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__1__KET____DOT__stage_inst__DOT__w_imag;
        VlUnpacked<SData/*15:0*/, 3> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__1__KET____DOT__stage_inst__DOT__b0__DOT__u_delay_a__DOT__genblk1__DOT__delay_line;
        VlUnpacked<SData/*15:0*/, 3> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__1__KET____DOT__stage_inst__DOT__b0__DOT__u_delay_ai__DOT__genblk1__DOT__delay_line;
        VlUnpacked<CData/*0:0*/, 4> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__1__KET____DOT__stage_inst__DOT__b0__DOT__u_delay_start__DOT__genblk1__DOT__delay_line;
        VlUnpacked<SData/*15:0*/, 1> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__1__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db0__DOT__buf_re;
        VlUnpacked<SData/*15:0*/, 1> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__1__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db0__DOT__buf_im;
    };
    struct {
        VlUnpacked<SData/*15:0*/, 2> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__1__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db1__DOT__buf_re;
        VlUnpacked<SData/*15:0*/, 2> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__1__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db1__DOT__buf_im;
        VlUnpacked<CData/*7:0*/, 4> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__2__KET____DOT__stage_inst__DOT__w_real;
        VlUnpacked<CData/*7:0*/, 4> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__2__KET____DOT__stage_inst__DOT__w_imag;
        VlUnpacked<SData/*15:0*/, 3> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__2__KET____DOT__stage_inst__DOT__b0__DOT__u_delay_a__DOT__genblk1__DOT__delay_line;
        VlUnpacked<SData/*15:0*/, 3> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__2__KET____DOT__stage_inst__DOT__b0__DOT__u_delay_ai__DOT__genblk1__DOT__delay_line;
        VlUnpacked<CData/*0:0*/, 4> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__2__KET____DOT__stage_inst__DOT__b0__DOT__u_delay_start__DOT__genblk1__DOT__delay_line;
        VlUnpacked<SData/*15:0*/, 2> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__2__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db0__DOT__buf_re;
        VlUnpacked<SData/*15:0*/, 2> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__2__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db0__DOT__buf_im;
        VlUnpacked<SData/*15:0*/, 4> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__2__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db1__DOT__buf_re;
        VlUnpacked<SData/*15:0*/, 4> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__2__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db1__DOT__buf_im;
        VlUnpacked<CData/*7:0*/, 8> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__3__KET____DOT__stage_inst__DOT__w_real;
        VlUnpacked<CData/*7:0*/, 8> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__3__KET____DOT__stage_inst__DOT__w_imag;
        VlUnpacked<SData/*15:0*/, 3> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__3__KET____DOT__stage_inst__DOT__b0__DOT__u_delay_a__DOT__genblk1__DOT__delay_line;
        VlUnpacked<SData/*15:0*/, 3> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__3__KET____DOT__stage_inst__DOT__b0__DOT__u_delay_ai__DOT__genblk1__DOT__delay_line;
        VlUnpacked<CData/*0:0*/, 4> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__3__KET____DOT__stage_inst__DOT__b0__DOT__u_delay_start__DOT__genblk1__DOT__delay_line;
        VlUnpacked<SData/*15:0*/, 4> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__3__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db0__DOT__buf_re;
        VlUnpacked<SData/*15:0*/, 4> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__3__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db0__DOT__buf_im;
        VlUnpacked<SData/*15:0*/, 8> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__3__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db1__DOT__buf_re;
        VlUnpacked<SData/*15:0*/, 8> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__3__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db1__DOT__buf_im;
        VlUnpacked<CData/*7:0*/, 16> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__4__KET____DOT__stage_inst__DOT__w_real;
        VlUnpacked<CData/*7:0*/, 16> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__4__KET____DOT__stage_inst__DOT__w_imag;
        VlUnpacked<SData/*15:0*/, 3> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__4__KET____DOT__stage_inst__DOT__b0__DOT__u_delay_a__DOT__genblk1__DOT__delay_line;
        VlUnpacked<SData/*15:0*/, 3> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__4__KET____DOT__stage_inst__DOT__b0__DOT__u_delay_ai__DOT__genblk1__DOT__delay_line;
        VlUnpacked<CData/*0:0*/, 4> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__4__KET____DOT__stage_inst__DOT__b0__DOT__u_delay_start__DOT__genblk1__DOT__delay_line;
        VlUnpacked<SData/*15:0*/, 8> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__4__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db0__DOT__buf_re;
        VlUnpacked<SData/*15:0*/, 8> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__4__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db0__DOT__buf_im;
        VlUnpacked<SData/*15:0*/, 16> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__4__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db1__DOT__buf_re;
        VlUnpacked<SData/*15:0*/, 16> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__4__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db1__DOT__buf_im;
        VlUnpacked<CData/*7:0*/, 32> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__5__KET____DOT__stage_inst__DOT__w_real;
        VlUnpacked<CData/*7:0*/, 32> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__5__KET____DOT__stage_inst__DOT__w_imag;
        VlUnpacked<SData/*15:0*/, 3> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__5__KET____DOT__stage_inst__DOT__b0__DOT__u_delay_a__DOT__genblk1__DOT__delay_line;
        VlUnpacked<SData/*15:0*/, 3> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__5__KET____DOT__stage_inst__DOT__b0__DOT__u_delay_ai__DOT__genblk1__DOT__delay_line;
        VlUnpacked<CData/*0:0*/, 4> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__5__KET____DOT__stage_inst__DOT__b0__DOT__u_delay_start__DOT__genblk1__DOT__delay_line;
        VlUnpacked<SData/*15:0*/, 16> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__5__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db0__DOT__buf_re;
        VlUnpacked<SData/*15:0*/, 16> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__5__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db0__DOT__buf_im;
        VlUnpacked<SData/*15:0*/, 32> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__5__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db1__DOT__buf_re;
        VlUnpacked<SData/*15:0*/, 32> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__5__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db1__DOT__buf_im;
        VlUnpacked<CData/*7:0*/, 64> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__6__KET____DOT__stage_inst__DOT__w_real;
        VlUnpacked<CData/*7:0*/, 64> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__6__KET____DOT__stage_inst__DOT__w_imag;
        VlUnpacked<SData/*15:0*/, 3> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__6__KET____DOT__stage_inst__DOT__b0__DOT__u_delay_a__DOT__genblk1__DOT__delay_line;
        VlUnpacked<SData/*15:0*/, 3> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__6__KET____DOT__stage_inst__DOT__b0__DOT__u_delay_ai__DOT__genblk1__DOT__delay_line;
        VlUnpacked<CData/*0:0*/, 4> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__6__KET____DOT__stage_inst__DOT__b0__DOT__u_delay_start__DOT__genblk1__DOT__delay_line;
        VlUnpacked<SData/*15:0*/, 32> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__6__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db0__DOT__buf_re;
        VlUnpacked<SData/*15:0*/, 32> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__6__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db0__DOT__buf_im;
        VlUnpacked<SData/*15:0*/, 64> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__6__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db1__DOT__buf_re;
        VlUnpacked<SData/*15:0*/, 64> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__6__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db1__DOT__buf_im;
        VlUnpacked<CData/*7:0*/, 128> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__7__KET____DOT__stage_inst__DOT__w_real;
        VlUnpacked<CData/*7:0*/, 128> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__7__KET____DOT__stage_inst__DOT__w_imag;
        VlUnpacked<SData/*15:0*/, 3> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__7__KET____DOT__stage_inst__DOT__b0__DOT__u_delay_a__DOT__genblk1__DOT__delay_line;
        VlUnpacked<SData/*15:0*/, 3> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__7__KET____DOT__stage_inst__DOT__b0__DOT__u_delay_ai__DOT__genblk1__DOT__delay_line;
        VlUnpacked<CData/*0:0*/, 4> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__7__KET____DOT__stage_inst__DOT__b0__DOT__u_delay_start__DOT__genblk1__DOT__delay_line;
        VlUnpacked<SData/*15:0*/, 64> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__7__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db0__DOT__buf_re;
        VlUnpacked<SData/*15:0*/, 64> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__7__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db0__DOT__buf_im;
        VlUnpacked<SData/*15:0*/, 128> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__7__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db1__DOT__buf_re;
        VlUnpacked<SData/*15:0*/, 128> tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__7__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db1__DOT__buf_im;
    };
    VlDelayScheduler __VdlySched;
    VlTriggerScheduler __VtrigSched_h121e40a7__0;
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<3> __VactTriggered;
    VlTriggerVec<3> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vtb_radix2_top__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vtb_radix2_top___024root(Vtb_radix2_top__Syms* symsp, const char* v__name);
    ~Vtb_radix2_top___024root();
    VL_UNCOPYABLE(Vtb_radix2_top___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
