// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design implementation internals
// See Vtb_radix2_top.h for the primary calling header

#include "Vtb_radix2_top__pch.h"
#include "Vtb_radix2_top__Syms.h"
#include "Vtb_radix2_top___024root.h"

void Vtb_radix2_top___024root___nba_sequent__TOP__0(Vtb_radix2_top___024root* vlSelf);
void Vtb_radix2_top___024root___nba_sequent__TOP__1(Vtb_radix2_top___024root* vlSelf);
void Vtb_radix2_top___024root___nba_sequent__TOP__2(Vtb_radix2_top___024root* vlSelf);
void Vtb_radix2_top___024root___nba_sequent__TOP__3(Vtb_radix2_top___024root* vlSelf);
void Vtb_radix2_top___024root___nba_sequent__TOP__4(Vtb_radix2_top___024root* vlSelf);
void Vtb_radix2_top_DelayBuffer__D100_W18___nba_sequent__TOP__tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__8__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db1__0(Vtb_radix2_top_DelayBuffer__D100_W18* vlSelf);
void Vtb_radix2_top_DelayBuffer__D100_W18___nba_sequent__TOP__tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__9__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db0__0(Vtb_radix2_top_DelayBuffer__D100_W18* vlSelf);
void Vtb_radix2_top_DelayBuffer__D200_W18___nba_sequent__TOP__tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__9__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db1__0(Vtb_radix2_top_DelayBuffer__D200_W18* vlSelf);
void Vtb_radix2_top_DelayBuffer__D200_W18___nba_sequent__TOP__tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__10__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db0__0(Vtb_radix2_top_DelayBuffer__D200_W18* vlSelf);
void Vtb_radix2_top_DelayBuffer__D400_W18___nba_sequent__TOP__tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__10__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db1__0(Vtb_radix2_top_DelayBuffer__D400_W18* vlSelf);
void Vtb_radix2_top_DelayBuffer__D400_W18___nba_sequent__TOP__tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__10__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db1__1(Vtb_radix2_top_DelayBuffer__D400_W18* vlSelf);
void Vtb_radix2_top_DelayBuffer__D400_W18___nba_sequent__TOP__tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__11__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db0__1(Vtb_radix2_top_DelayBuffer__D400_W18* vlSelf);
void Vtb_radix2_top___024root___nba_sequent__TOP__5(Vtb_radix2_top___024root* vlSelf);
void Vtb_radix2_top_DelayBuffer__D400_W18___nba_sequent__TOP__tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__10__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db1__2(Vtb_radix2_top_DelayBuffer__D400_W18* vlSelf);
void Vtb_radix2_top_DelayBuffer__D200_W18___nba_sequent__TOP__tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__10__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db0__1(Vtb_radix2_top_DelayBuffer__D200_W18* vlSelf);
void Vtb_radix2_top_DelayBuffer__D200_W18___nba_sequent__TOP__tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__9__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db1__1(Vtb_radix2_top_DelayBuffer__D200_W18* vlSelf);
void Vtb_radix2_top_DelayBuffer__D100_W18___nba_sequent__TOP__tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__9__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db0__1(Vtb_radix2_top_DelayBuffer__D100_W18* vlSelf);
void Vtb_radix2_top_DelayBuffer__D100_W18___nba_sequent__TOP__tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__8__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db1__1(Vtb_radix2_top_DelayBuffer__D100_W18* vlSelf);

void Vtb_radix2_top___024root___eval_nba(Vtb_radix2_top___024root* vlSelf) {
    if (false && vlSelf) {}  // Prevent unused
    Vtb_radix2_top__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtb_radix2_top___024root___eval_nba\n"); );
    // Body
    if ((1ULL & vlSelf->__VnbaTriggered.word(0U))) {
        Vtb_radix2_top___024root___nba_sequent__TOP__0(vlSelf);
        Vtb_radix2_top___024root___nba_sequent__TOP__1(vlSelf);
        Vtb_radix2_top___024root___nba_sequent__TOP__2(vlSelf);
        Vtb_radix2_top___024root___nba_sequent__TOP__3(vlSelf);
        Vtb_radix2_top___024root___nba_sequent__TOP__4(vlSelf);
        Vtb_radix2_top_DelayBuffer__D100_W18___nba_sequent__TOP__tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__8__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db1__0((&vlSymsp->TOP__tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__8__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db1));
        Vtb_radix2_top_DelayBuffer__D100_W18___nba_sequent__TOP__tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__9__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db0__0((&vlSymsp->TOP__tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__9__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db0));
        Vtb_radix2_top_DelayBuffer__D200_W18___nba_sequent__TOP__tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__9__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db1__0((&vlSymsp->TOP__tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__9__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db1));
        Vtb_radix2_top_DelayBuffer__D200_W18___nba_sequent__TOP__tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__10__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db0__0((&vlSymsp->TOP__tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__10__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db0));
        Vtb_radix2_top_DelayBuffer__D400_W18___nba_sequent__TOP__tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__10__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db1__0((&vlSymsp->TOP__tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__10__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db1));
        Vtb_radix2_top_DelayBuffer__D400_W18___nba_sequent__TOP__tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__10__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db1__1((&vlSymsp->TOP__tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__10__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db1));
        Vtb_radix2_top_DelayBuffer__D400_W18___nba_sequent__TOP__tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__10__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db1__0((&vlSymsp->TOP__tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__11__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db0));
        Vtb_radix2_top_DelayBuffer__D400_W18___nba_sequent__TOP__tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__11__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db0__1((&vlSymsp->TOP__tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__11__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db0));
        Vtb_radix2_top___024root___nba_sequent__TOP__5(vlSelf);
        Vtb_radix2_top_DelayBuffer__D400_W18___nba_sequent__TOP__tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__10__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db1__2((&vlSymsp->TOP__tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__10__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db1));
        Vtb_radix2_top_DelayBuffer__D200_W18___nba_sequent__TOP__tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__10__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db0__1((&vlSymsp->TOP__tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__10__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db0));
        Vtb_radix2_top_DelayBuffer__D200_W18___nba_sequent__TOP__tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__9__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db1__1((&vlSymsp->TOP__tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__9__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db1));
        Vtb_radix2_top_DelayBuffer__D100_W18___nba_sequent__TOP__tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__9__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db0__1((&vlSymsp->TOP__tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__9__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db0));
        Vtb_radix2_top_DelayBuffer__D100_W18___nba_sequent__TOP__tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__8__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db1__1((&vlSymsp->TOP__tb_radix2_top__DOT__dut__DOT__gen_stages__BRA__8__KET____DOT__stage_inst__DOT__gen_delay_buffers__DOT__db1));
    }
}
